name: Deploy

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x

      - run: deno fmt --check
      - run: deno lint
      - run: deno test

  deploy:
    needs: validate
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "school-rd-api" # the name of the project on Deno Deploy
          entrypoint: ./src/main.ts # the entrypoint to deploy

